{
 "title": "Init",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "custom counter rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "rate(my_custom_counter[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "system_runtime_cpu_usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "system_runtime_cpu_usage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "request_duration percentile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(microsoft_aspnetcore_hosting_http_server_request_duration_bucket[5m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "process_private_memory_bytes gb",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_private_memory_bytes / 1024 / 1024 / 1025",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "avg req duration last 5 mins",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum by(le) (rate(microsoft_aspnetcore_hosting_http_server_request_duration_bucket{http_request_method=\"GET\", http_response_status_code=\"200\", http_route=\"WeatherForecast\", network_protocol_version=\"1.1\", url_scheme=\"http\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}