version: '3.7'

services:
  webapi:
    build: .
    ports:
      - "80:80"
      - "443:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*80
    networks:
      - webnet

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - webnet
    depends_on:
      - webapi

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - webnet
    depends_on:
      - prometheus

networks:
  webnet:
